version: '3'

services:
  irisnode0:
    container_name: irisnode0
    image: "tendermint/irisnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-iris.log}
    volumes:
      - ./build:/iris:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  irisnode1:
    container_name: irisnode1
    image: "tendermint/irisnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-iris.log}
    volumes:
      - ./build:/iris:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  irisnode2:
    container_name: irisnode2
    image: "tendermint/irisnode"
    environment:
      - ID=2
      - LOG=${LOG:-iris.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/iris:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  irisnode3:
    container_name: irisnode3
    image: "tendermint/irisnode"
    environment:
      - ID=3
      - LOG=${LOG:-iris.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/iris:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

